#!/bin/bash

# test for loop

# 如果省略掉 for 命令的可选项 words 部分，for 命令会默认处理位置参数

# 练习1

# while [[ -n $1 ]]; do
#   if [[ -r $1 ]]; then
#     maxlength=0
#     maxword=
#     for i in $(strings $1); do #strings $1表示读取该文件($1)的words列表
#       len=$(echo $i|wc -c) #statements
#       # echo "'$1' file word is $i and length is $len" # 测试打印每个单词
#       if [[ len -gt $maxlength ]]; then # 或者写成 if (( len > $maxlength ))
#         maxlength=$len
#         maxword=$i
#       fi
#     done
#     echo "$1: '$maxword' max length is $maxlength !"
#   fi  #statements
#   shift
# done

# 练习2

# 如果for循环里去掉位置参数 则会默认处理位置参数


# longest-word2 : find longest string in a file
for i; do
    if [[ -r $i ]]; then
        max_word=
        max_len=0
        for j in $(strings $i); do
            len=$(echo $j | wc -c)
            if (( len > max_len )); then
                max_len=$len
                max_word=$j
            fi
        done
        echo "$i: '$max_word' ($max_len characters)"
    fi
done
